module.exports = {
  AZUREAD_TOKEN_CONFIG: {
    jwksUri: process.env.AZUREAD_JWK_URI,
    issuer: process.env.AZUREAD_ISSUER_URI,
    audience: process.env.AZUREAD_CLIENTID
  },
  STORAGE: {
    AZURE_BLOB_CONNECTIONSTRING: process.env.AZURE_BLOB_CONNECTIONSTRING,
    AZURE_BLOB_CONTAINERNAME: process.env.AZURE_BLOB_CONTAINERNAME,
    MONGODB_CONNECTIONSTRING: process.env.MONGODB_CONNECTIONSTRING
  },
  GRAPH: {
    GRAPH_SCOPE: process.env.GRAPH_SCOPE,
    GRAPH_URL: process.env.GRAPH_URL
  },
  MATRIKKEL: {
    MATRIKKEL_BASEURL: process.env.MATRIKKEL_BASEURL,
    MATRIKKEL_KEY: process.env.MATRIKKEL_KEY,
    MATRIKKEL_SCOPE: process.env.MATRIKKEL_SCOPE,
    MATRIKKEL_APP_REG_CLIENT_ID: process.env.MATRIKKEL_APP_REG_CLIENT_ID,
    MATRIKKEL_APP_REG_CLIENT_SECRET: process.env.MATRIKKEL_APP_REG_CLIENT_SECRET
  },
  PDFGENERATOR: {
    PDFGENERATOR_ENDPOINT: process.env.PDFGENERATOR_ENDPOINT,
    PDFGENERATOR_X_FUNCTIONS_KEY: process.env.PDFGENERATOR_X_FUNCTIONS_KEY
  },
  ARCHIVE: {
    ARCHIVE_ENDPOINT: process.env.ARCHIVE_URL,
    ARCHIVE_SCOPE: process.env.ARCHIVE_SCOPE,
    ARCHIVE_APP_REG_CLIENT_ID: process.env.ARCHIVE_APP_REG_CLIENT_ID,
    ARCHIVE_APP_REG_CLIENT_SECRET: process.env.ARCHIVE_APP_REG_CLIENT_SECRET
  },
  STATISTICS: {
    STATISTICS_KEY: process.env.STATISTICS_KEY,
    STATISTICS_URL: process.env.STATISTICS_URL
  },
  MS: {
    TENANT_ID: process.env.APP_REG_TENANT_ID,
    AZUREAD_ALLOWEDGROUPS: process.env.AZUREAD_ALLOWEDGROUPS,
    TEAMS_WEBHOOK_URL: process.env.TEAMS_WEBHOOK_URL
  },
  MISC: {
    BYPASS_REGISTRATION_THRESHOLD: process.env.BYPASS_REGISTRATION_THRESHOLD || true
  },
  PAPERTRAIL: {
    PAPERTRAIL_HOST: process.env.PAPERTRAIL_HOST,
    PAPERTRAIL_TOKEN: process.env.PAPERTRAIL_TOKEN
  },
  MASSEUTSENDELSE: {
    MASSEUTSENDELSE_APP_REG_CLIENT_ID: process.env.MASSEUTSENDELSE_APP_REG_CLIENT_ID,
    MASSEUTSENDELSE_APP_REG_CLIENT_SECRET: process.env.MASSEUTSENDELSE_APP_REG_CLIENT_SECRET,
    MASSEUTSENDELSE_SCOPE: process.env.MASSEUTSENDELSE_SCOPE
  }

  // APIKEYS: process.env.APIKEYS,
  // APIKEYS_MINIMUM_LENGTH: process.env.APIKEYS_MINIMUM_LENGTH || 24,
}
