module.exports = {
  AZUREAD_TOKEN_CONFIG: {
    jwksUri: process.env.AZUREAD_JWK_URI,
    issuer: process.env.AZUREAD_ISSUER_URI,
    audience: process.env.AZUREAD_CLIENTID
  },
  STORAGE: {
    AZURE_BLOB_CONNECTIONSTRING: process.env.AZURE_BLOB_CONNECTIONSTRING,
    AZURE_BLOB_CONTAINERNAME: process.env.AZURE_BLOB_CONTAINERNAME,
    MONGODB_CONNECTIONSTRING: process.env.MONGODB_CONNECTIONSTRING
  },
  GRAPH: {
    GRAPH_SCOPE: process.env.GRAPH_SCOPE,
    GRAPH_URL: process.env.GRAPH_URL
  },
  MATRIKKEL: {
    MATRIKKEL_BASEURL: process.env.MATRIKKEL_BASEURL,
    MATRIKKEL_KEY: process.env.MATRIKKEL_KEY,
    MATRIKKEL_SCOPE: process.env.MATRIKKEL_SCOPE
  },
  PDF_GENERATOR: {
    PDF_GENERATOR_ENDPOINT: process.env.PDFGENERATOR_ENDPOINT,
    PDF_GENERATOR_X_FUNCTIONS_KEY: process.env.PDFGENERATOR_X_FUNCTIONS_KEY
  },
  ARCHIVE: {
    ARCHIVE_ENDPOINT: process.env.ARCHIVE_URL,
    ARCHIVE_SCOPE: process.env.ARCHIVE_SCOPE,
    ARCHIVE_SHOW_DISPATCH_URL: process.env.ARCHIVE_SHOW_DISPATCH_URL
  },
  STATISTICS: {
    STATISTICS_KEY: process.env.STATISTICS_KEY,
    STATISTICS_URL: process.env.STATISTICS_URL
  },
  MS: {
    AZUREAD_ALLOWEDGROUPS: process.env.AZUREAD_ALLOWEDGROUPS,
    AZUREAD_SKIP_DEPARTMENT_CHECK: process.env.AZUREAD_SKIP_DEPARTMENT_CHECK?.toLowerCase().split(",") || [],
    AZUREAD_SKIP_DEPARTMENT_NAME: process.env.AZUREAD_SKIP_DEPARTMENT_NAME || "Kode-Kæll",
    TEAMS_ALERTS_WEBHOOK_URL: process.env.TEAMS_ALERTS_WEBHOOK_URL
  },
  MISC: {
    BYPASS_REGISTRATION_THRESHOLD: process.env.BYPASS_REGISTRATION_THRESHOLD || true
  }

  // APIKEYS: process.env.APIKEYS,
  // APIKEYS_MINIMUM_LENGTH: process.env.APIKEYS_MINIMUM_LENGTH || 24,
};
